#!/bin/bash

build-rails() {
  echo -e "\nBuilding $1-rails"
  cat > Dockerfile-rails <<EOF
FROM ruby-consul:$1

COPY scripts/run-rails /scripts/run-rails
ENTRYPOINT ["/scripts/run-rails"]
EOF
  docker build -t ruby-consul:$1-rails -f Dockerfile-rails .
  rm Dockerfile-rails
}

versions=(2.1.5 2.3.0)
for i in ${versions[@]}; do
  echo -e "\nBuilding $i"
  docker build -t ruby-consul:$i -f $i/Dockerfile .
  build-rails $i
done
