#!/bin/bash

# rbenv install echos enough by itself
if [ -z $RBENV_VERSION ]; then
  if [ -f .ruby-version ]; then
    RBENV_VERSION=$(cat .ruby-version)
  else
    echo "RBENV_VERSION not set and no .ruby-version file exists. Exiting."
    exit 1
  fi
fi
source ~/.bashrc
installed=`rbenv versions 2>&1 | grep $RBENV_VERSION | grep -v 'not installed'|wc -l|tr -d '[:space:]'`
if [ $installed -ne '1' ]; then
  rbenv install -s $RBENV_VERSION
fi

echo "Installing bundler & gems"
gem install bundler
bundle install

echo "Setting Consul Log Level"
if [ ! -z $CONSUL_LOG_LEVEL ]; then
  log_level=$CONSUL_LOG_LEVEL
else
  log_level=warn
fi

echo "Configuring SSH Keys"
if [ -d /ssh_keys ]; then
  cp -Rf /ssh_keys ~/.ssh
  eval "$(ssh-agent)" > /dev/null 2>&1
  ssh-add > /dev/null 2>&1
fi

echo "Starting envconsul"
/usr/local/bin/envconsul \
  -sanitize \
  -upcase \
  -log-level=$log_level \
  -consul=$CONSUL_HOST:8500 \
  $CONSUL_PREFIXES \
  "$@"
