#!/bin/bash

if [ ! -z $CONSUL_LOG_LEVEL ]; then
  log_level=$CONSUL_LOG_LEVEL
else
  log_level=warn
fi

if [ -d /ssh_keys ]; then
  cp -Rf /ssh_keys ~/.ssh
  eval "$(ssh-agent)" > /dev/null 2>&1
  ssh-add > /dev/null 2>&1
fi

/usr/local/bin/envconsul \
  -sanitize \
  -upcase \
  -log-level=$log_level \
  -consul=$CONSUL_HOST:8500 \
  $CONSUL_PREFIXES \
  "$@"
