#!/bin/bash

if [ -z $RBENV_VERSION ]; then
  if [ -f .ruby-version ]; then
    RBENV_VERSION=$(cat .ruby-version)
  else
    echo "RBENV_VERSION not set and no .ruby-version file exists. Exiting."
    exit 1
  fi
fi

source ~/.bashrc
rbenv install -s $RBENV_VERSION

if [ ! -z $CONSUL_LOG_LEVEL ]; then
  log_level=$CONSUL_LOG_LEVEL
else
  log_level=warn
fi

if [ -d /ssh_keys ]; then
  cp -Rf /ssh_keys ~/.ssh
  eval "$(ssh-agent)" > /dev/null 2>&1
  ssh-add > /dev/null 2>&1
fi

/usr/local/bin/envconsul \
  -sanitize \
  -upcase \
  -log-level=$log_level \
  -consul=$CONSUL_HOST:8500 \
  $CONSUL_PREFIXES \
  "$@"
